import {
  BarChart3,
  Blocks,
  Brain,
  ClipboardList,
  Cloud,
  Code,
  Cog,
  Database,
  Gamepad2,
  Layers,
  Network,
  Server,
  Shield,
  Smartphone,
  Notebook as Robot,
} from "lucide-react";

export const InterviewTopics = [
  { value: "frontend", label: "Frontend Development" },
  { value: "backend", label: "Backend Development" },
  { value: "devops", label: "DevOps" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "fullstack", label: "Fullstack Development" },
  { value: "ai-engineer", label: "AI Engineer" },
  { value: "data-analyst", label: "Data Analyst" },
  { value: "ios", label: "iOS Development" },
  { value: "blockchain", label: "Blockchain Development" },
  { value: "game-dev", label: "Game Development" },
  { value: "cloud", label: "Cloud Computing" },
  { value: "ml", label: "Machine Learning" },
  { value: "networking", label: "Networking" },
  { value: "dba", label: "Database Administration" },
  { value: "pm", label: "IT Project Management" },
] as const;

export const topicIcons = {
  frontend: Code,
  backend: Server,
  devops: Cog,
  cybersecurity: Shield,
  fullstack: Layers,
  "ai-engineer": Robot,
  "data-analyst": BarChart3,
  ios: Smartphone,
  blockchain: Blocks,
  "game-dev": Gamepad2,
  cloud: Cloud,
  ml: Brain,
  networking: Network,
  dba: Database,
  pm: ClipboardList,
} as const;

export const DifficultyLevels = [
  { value: 1, label: "Basic" },
  { value: 2, label: "Intermediate" },
  { value: 3, label: "Advanced" },
  { value: 4, label: "Expert" },
  { value: 5, label: "Master" },
] as const;
